### ISSUE TITLE
example of Dotty features in Docs does not compile

### ISSUE THREAD

**Issue by weihsiu** [MaximeKjaer/tf-dotty#6] opened 2020-03-04 09:34 UTC
the following example in the section on Dotty features does not compile.  the compile error is `Cyclic reference involving type GCD`.  the dotty version i am using is 0.22.0-RC1(same as the latest build).
```
import scala.compiletime.ops.int.%

type GCD[A <: Int, B <: Int] <: Int = B match {
    case 0 => A
    case _ => GCD[B, A % B]
}
```

**Comment by weihsiu** [comment] 2020-03-04 09:39
I am sorry i didn't read the doc thoroughly.  i guess the feature above is not yet implemented in the official dotty.  sorry for the noise.

**Comment by MaximeKjaer** [comment] 2020-03-04 10:27
This is weird! The example *should* compile in Dotty 0.22.0-RC1. I'm able to compile it on my machine, and there's even a [test for this example in Dotty](https://github.com/lampepfl/dotty/blob/04042381ff99039884cd85d87e22f1463b8133cf/tests/neg/singleton-ops-recursive-match-type.scala).

Can you maybe check that you are indeed compiling with the latest Dotty release?

**Comment by MaximeKjaer** [comment] 2020-12-10 13:18
Closing for now as I am unable to reproduce the error.

**Closed by MaximeKjaer** 2020-12-10 13:18 UTC
